<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 PREDICCIÓN DE ORDENES - SERIES DE TIEMPO | Series de tiempo - Online Retail</title>
  <meta name="description" content="Análisis de series de tiempo aplicadas al comportamiento de compras online del 2010 al 2011" />
  <meta name="generator" content="bookdown 0.42 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 PREDICCIÓN DE ORDENES - SERIES DE TIEMPO | Series de tiempo - Online Retail" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Análisis de series de tiempo aplicadas al comportamiento de compras online del 2010 al 2011" />
  <meta name="github-repo" content="looocust/TimeSeries" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 PREDICCIÓN DE ORDENES - SERIES DE TIEMPO | Series de tiempo - Online Retail" />
  
  <meta name="twitter:description" content="Análisis de series de tiempo aplicadas al comportamiento de compras online del 2010 al 2011" />
  

<meta name="author" content="Joaquin Mejia &amp; Deisy Forero" />


<meta name="date" content="2025-05-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="introducción.html"/>
<link rel="next" href="referencias.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Propuesta de análisis</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#tema-pronóstico-de-comportamiento-de-compras-en-e-commerce"><i class="fa fa-check"></i><b>1.1</b> Tema: Pronóstico de comportamiento de compras en e-commerce</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="index.html"><a href="index.html#justificación"><i class="fa fa-check"></i><b>1.1.1</b> Justificación</a></li>
<li class="chapter" data-level="1.1.2" data-path="index.html"><a href="index.html#fuente-de-datos"><i class="fa fa-check"></i><b>1.1.2</b> Fuente de datos</a></li>
<li class="chapter" data-level="1.1.3" data-path="index.html"><a href="index.html#licencia-y-permisos"><i class="fa fa-check"></i><b>1.1.3</b> Licencia y permisos</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i><b>2</b> Introducción</a></li>
<li class="chapter" data-level="3" data-path="predicción-de-ordenes---series-de-tiempo.html"><a href="predicción-de-ordenes---series-de-tiempo.html"><i class="fa fa-check"></i><b>3</b> PREDICCIÓN DE ORDENES - SERIES DE TIEMPO</a>
<ul>
<li class="chapter" data-level="3.1" data-path="predicción-de-ordenes---series-de-tiempo.html"><a href="predicción-de-ordenes---series-de-tiempo.html#transformación-box-cox"><i class="fa fa-check"></i><b>3.1</b> Transformación Box-Cox</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="predicción-de-ordenes---series-de-tiempo.html"><a href="predicción-de-ordenes---series-de-tiempo.html#suavizamiento-exponencial-el-promedio-móvil-y-holt-winter"><i class="fa fa-check"></i><b>3.1.1</b> Suavizamiento exponencial, el promedio móvil y Holt-Winter</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="predicción-de-ordenes---series-de-tiempo.html"><a href="predicción-de-ordenes---series-de-tiempo.html#pronóstico-con-modelo-holt-winters-aditivo"><i class="fa fa-check"></i><b>3.2</b> Pronóstico con modelo Holt-Winters aditivo</a></li>
<li class="chapter" data-level="3.3" data-path="predicción-de-ordenes---series-de-tiempo.html"><a href="predicción-de-ordenes---series-de-tiempo.html#evaluación-y-comparación-de-precisión-ses-vs-holt-winters"><i class="fa fa-check"></i><b>3.3</b> Evaluación y comparación de precisión: SES vs Holt-Winters</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="predicción-de-ordenes---series-de-tiempo.html"><a href="predicción-de-ordenes---series-de-tiempo.html#análisis"><i class="fa fa-check"></i><b>3.3.1</b> Análisis:</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i><b>4</b> Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Series de tiempo - Online Retail</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="predicción-de-ordenes---series-de-tiempo" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> PREDICCIÓN DE ORDENES - SERIES DE TIEMPO<a href="predicción-de-ordenes---series-de-tiempo.html#predicción-de-ordenes---series-de-tiempo" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-1" tabindex="-1"></a><span class="co"># Se instala lo necesario para proceder</span></span>
<span id="cb1-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-2" tabindex="-1"></a></span>
<span id="cb1-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-3" tabindex="-1"></a><span class="fu">library</span>(tidyverse)   <span class="co"># dplyr, ggplot2, etc.</span></span>
<span id="cb1-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-4" tabindex="-1"></a><span class="fu">library</span>(readxl)      <span class="co"># leer archivos .xlsx</span></span>
<span id="cb1-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-5" tabindex="-1"></a><span class="fu">library</span>(lubridate)   <span class="co"># manejo de fechas</span></span>
<span id="cb1-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-6" tabindex="-1"></a><span class="fu">library</span>(zoo)         <span class="co"># promedios móviles</span></span>
<span id="cb1-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-7" tabindex="-1"></a><span class="fu">library</span>(forecast)    <span class="co"># funciones de series de tiempo</span></span>
<span id="cb1-8"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-8" tabindex="-1"></a><span class="fu">library</span>(knitr)       <span class="co"># Resultados en tablas</span></span>
<span id="cb1-9"><a href="predicción-de-ordenes---series-de-tiempo.html#cb1-9" tabindex="-1"></a><span class="fu">library</span>(ggplot2)    <span class="co"># Graficos</span></span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb2-1" tabindex="-1"></a><span class="co"># Leer la primera hoja (cámbiala con `sheet =` si hiciera falta)</span></span>
<span id="cb2-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb2-2" tabindex="-1"></a>retail <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;Online Retail 2.xlsx&quot;</span>)</span>
<span id="cb2-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb2-3" tabindex="-1"></a></span>
<span id="cb2-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb2-4" tabindex="-1"></a><span class="co"># Vistazo rápido a la estructura</span></span>
<span id="cb2-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb2-5" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(retail)</span></code></pre></div>
<pre><code>## Rows: 541,909
## Columns: 8
## $ InvoiceNo   &lt;chr&gt; &quot;536365&quot;, &quot;536365&quot;, &quot;536365&quot;, &quot;536365&quot;, &quot;536365&quot;, &quot;536365&quot;…
## $ StockCode   &lt;chr&gt; &quot;85123A&quot;, &quot;71053&quot;, &quot;84406B&quot;, &quot;84029G&quot;, &quot;84029E&quot;, &quot;22752&quot;, …
## $ Description &lt;chr&gt; &quot;WHITE HANGING HEART T-LIGHT HOLDER&quot;, &quot;WHITE METAL LANTERN…
## $ Quantity    &lt;dbl&gt; 6, 6, 8, 6, 6, 2, 6, 6, 6, 32, 6, 6, 8, 6, 6, 3, 2, 3, 3, …
## $ InvoiceDate &lt;dttm&gt; 2010-12-01 08:26:00, 2010-12-01 08:26:00, 2010-12-01 08:2…
## $ UnitPrice   &lt;dbl&gt; 2.55, 3.39, 2.75, 3.39, 3.39, 7.65, 4.25, 1.85, 1.85, 1.69…
## $ CustomerID  &lt;dbl&gt; 17850, 17850, 17850, 17850, 17850, 17850, 17850, 17850, 17…
## $ Country     &lt;chr&gt; &quot;United Kingdom&quot;, &quot;United Kingdom&quot;, &quot;United Kingdom&quot;, &quot;Uni…</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-1" tabindex="-1"></a><span class="do">## --- 1. Agregar la cantidad por día ----------------------------------</span></span>
<span id="cb4-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-2" tabindex="-1"></a><span class="co"># Aseguramos que &#39;InvoiceDate&#39; sea fecha-hora y creamos la columna Date</span></span>
<span id="cb4-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-3" tabindex="-1"></a>retail <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> </span>
<span id="cb4-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">as.Date</span>(InvoiceDate))</span>
<span id="cb4-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-5" tabindex="-1"></a></span>
<span id="cb4-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-6" tabindex="-1"></a><span class="co"># Sumamos la cantidad vendida por día</span></span>
<span id="cb4-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-7" tabindex="-1"></a>daily_sales <span class="ot">&lt;-</span> retail <span class="sc">%&gt;%</span> </span>
<span id="cb4-8"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-8" tabindex="-1"></a>  <span class="fu">group_by</span>(Date) <span class="sc">%&gt;%</span> </span>
<span id="cb4-9"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-9" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">TotalQty =</span> <span class="fu">sum</span>(Quantity, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb4-10"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-10" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb4-11"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-11" tabindex="-1"></a></span>
<span id="cb4-12"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-12" tabindex="-1"></a><span class="do">## --- 2. Gráfico base de la serie diaria ------------------------------</span></span>
<span id="cb4-13"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-13" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb4-14"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-14" tabindex="-1"></a></span>
<span id="cb4-15"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-15" tabindex="-1"></a><span class="fu">ggplot</span>(daily_sales, <span class="fu">aes</span>(Date, TotalQty)) <span class="sc">+</span></span>
<span id="cb4-16"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-16" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;gray40&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-17"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-17" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Cantidad total vendida por día&quot;</span>,</span>
<span id="cb4-18"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-18" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Fecha&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Total de unidades&quot;</span>) <span class="sc">+</span></span>
<span id="cb4-19"><a href="predicción-de-ordenes---series-de-tiempo.html#cb4-19" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="series-online-retail_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb5-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-2" tabindex="-1"></a><span class="fu">library</span>(zoo)</span>
<span id="cb5-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-3" tabindex="-1"></a></span>
<span id="cb5-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-4" tabindex="-1"></a><span class="co"># Crear tabla con medias móviles</span></span>
<span id="cb5-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-5" tabindex="-1"></a>daily_ma <span class="ot">&lt;-</span> daily_sales <span class="sc">%&gt;%</span> </span>
<span id="cb5-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-6" tabindex="-1"></a>  <span class="fu">arrange</span>(Date) <span class="sc">%&gt;%</span> </span>
<span id="cb5-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-7" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb5-8"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-8" tabindex="-1"></a>    <span class="at">MA_7  =</span> zoo<span class="sc">::</span><span class="fu">rollmeanr</span>(TotalQty,  <span class="dv">7</span>, <span class="at">fill =</span> <span class="cn">NA</span>),</span>
<span id="cb5-9"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-9" tabindex="-1"></a>    <span class="at">MA_30 =</span> zoo<span class="sc">::</span><span class="fu">rollmeanr</span>(TotalQty, <span class="dv">30</span>, <span class="at">fill =</span> <span class="cn">NA</span>)</span>
<span id="cb5-10"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-10" tabindex="-1"></a>  )</span>
<span id="cb5-11"><a href="predicción-de-ordenes---series-de-tiempo.html#cb5-11" tabindex="-1"></a><span class="fu">names</span>(daily_ma)</span></code></pre></div>
<pre><code>## [1] &quot;Date&quot;     &quot;TotalQty&quot; &quot;MA_7&quot;     &quot;MA_30&quot;</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb7-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-2" tabindex="-1"></a></span>
<span id="cb7-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-3" tabindex="-1"></a><span class="fu">ggplot</span>(daily_ma, <span class="fu">aes</span>(Date)) <span class="sc">+</span></span>
<span id="cb7-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> TotalQty), <span class="at">colour =</span> <span class="st">&quot;grey70&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-5" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> MA_7),  <span class="at">colour =</span> <span class="st">&quot;blue&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> MA_30), <span class="at">colour =</span> <span class="st">&quot;green&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Promedios móviles de 7 y 30 días&quot;</span>,</span>
<span id="cb7-8"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Total de unidades&quot;</span>) <span class="sc">+</span></span>
<span id="cb7-9"><a href="predicción-de-ordenes---series-de-tiempo.html#cb7-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 6 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 29 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<p><img src="series-online-retail_files/figure-html/unnamed-chunk-3-1.png" width="672" />
La media móvil de 30 días (línea roja) muestra una tendencia ascendente clara desde mayo-2011, mientras que la de 7 días (azul) revela picos semanales.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb10-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb10-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-3" tabindex="-1"></a></span>
<span id="cb10-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-4" tabindex="-1"></a>daily_lag <span class="ot">&lt;-</span> daily_sales <span class="sc">%&gt;%</span>               <span class="co"># usamos la tabla diaria original</span></span>
<span id="cb10-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-5" tabindex="-1"></a>  <span class="fu">arrange</span>(Date) <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-6" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb10-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-7" tabindex="-1"></a>    <span class="at">Lag_1 =</span> dplyr<span class="sc">::</span><span class="fu">lag</span>(TotalQty, <span class="dv">1</span>),</span>
<span id="cb10-8"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-8" tabindex="-1"></a>    <span class="at">Lag_7 =</span> dplyr<span class="sc">::</span><span class="fu">lag</span>(TotalQty, <span class="dv">7</span>)</span>
<span id="cb10-9"><a href="predicción-de-ordenes---series-de-tiempo.html#cb10-9" tabindex="-1"></a>  )</span></code></pre></div>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb11-1" tabindex="-1"></a><span class="fu">ggplot</span>(daily_lag, <span class="fu">aes</span>(Date)) <span class="sc">+</span></span>
<span id="cb11-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb11-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> TotalQty), <span class="at">colour =</span> <span class="st">&quot;black&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb11-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Lag_1), <span class="at">colour =</span> <span class="st">&quot;orange&quot;</span>,  <span class="at">linetype =</span> <span class="st">&quot;dashed&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb11-4" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> Lag_7), <span class="at">colour =</span> <span class="st">&quot;purple&quot;</span>,  <span class="at">linetype =</span> <span class="st">&quot;dotted&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb11-5" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Serie comparada con rezagos de 1 y 7 días&quot;</span>,</span>
<span id="cb11-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb11-6" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Total de unidades&quot;</span>) <span class="sc">+</span></span>
<span id="cb11-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb11-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<pre><code>## Warning: Removed 7 rows containing missing values or values outside the scale range
## (`geom_line()`).</code></pre>
<p><img src="series-online-retail_files/figure-html/unnamed-chunk-4-1.png" width="672" />
La superposición con el rezago de 1 día (naranja) indica alta autocorrelación diaria; el rezago-7 (morado) refuerza la periodicidad semanal.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-1" tabindex="-1"></a><span class="fu">library</span>(forecast)   <span class="co"># ya lo tienes cargado</span></span>
<span id="cb14-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb14-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-3" tabindex="-1"></a></span>
<span id="cb14-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-4" tabindex="-1"></a><span class="co"># 1. Convertir la columna TotalQty en un objeto ts semanal</span></span>
<span id="cb14-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-5" tabindex="-1"></a>ts_qty <span class="ot">&lt;-</span> <span class="fu">ts</span>(daily_sales<span class="sc">$</span>TotalQty, <span class="at">frequency =</span> <span class="dv">7</span>)</span>
<span id="cb14-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-6" tabindex="-1"></a></span>
<span id="cb14-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-7" tabindex="-1"></a><span class="co"># 2. Descomponer con STL</span></span>
<span id="cb14-8"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-8" tabindex="-1"></a>decomp <span class="ot">&lt;-</span> <span class="fu">stl</span>(ts_qty, <span class="at">s.window =</span> <span class="st">&quot;periodic&quot;</span>)</span>
<span id="cb14-9"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-9" tabindex="-1"></a></span>
<span id="cb14-10"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-10" tabindex="-1"></a><span class="co"># 3. Graficar los componentes</span></span>
<span id="cb14-11"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-11" tabindex="-1"></a><span class="fu">autoplot</span>(decomp) <span class="sc">+</span></span>
<span id="cb14-12"><a href="predicción-de-ordenes---series-de-tiempo.html#cb14-12" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Descomposición STL: tendencia, estacionalidad y residuales&quot;</span>)</span></code></pre></div>
<p><img src="series-online-retail_files/figure-html/estacionalidad-1.png" width="672" />
El componente seasonal presenta oscilaciones regulares cada 7 puntos, confirmando efecto semanal; la tendencia suavizada muestra un crecimiento paulatino en la demanda.</p>
<p>PRUEBAS DE ESTACIONARIEDAD (ADF &amp; KPSS)</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb15-1" tabindex="-1"></a><span class="fu">library</span>(tseries)</span>
<span id="cb15-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb15-2" tabindex="-1"></a></span>
<span id="cb15-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb15-3" tabindex="-1"></a><span class="co">#––– 1. Dickey–Fuller aumentada –––#</span></span>
<span id="cb15-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb15-4" tabindex="-1"></a>adf_result  <span class="ot">&lt;-</span> <span class="fu">adf.test</span>(ts_qty, <span class="at">alternative =</span> <span class="st">&quot;stationary&quot;</span>)</span>
<span id="cb15-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb15-5" tabindex="-1"></a>adf_result<span class="sc">$</span>p.value      <span class="co"># &lt; 0.05  ⇒  estacionaria</span></span></code></pre></div>
<pre><code>## [1] 0.01</code></pre>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb17-1" tabindex="-1"></a><span class="co">#––– 2. KPSS (complementaria) –––#</span></span>
<span id="cb17-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb17-2" tabindex="-1"></a>kpss_result <span class="ot">&lt;-</span> <span class="fu">kpss.test</span>(ts_qty, <span class="at">null =</span> <span class="st">&quot;Level&quot;</span>)</span>
<span id="cb17-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb17-3" tabindex="-1"></a>kpss_result<span class="sc">$</span>p.value     <span class="co"># &gt; 0.05  ⇒  no se rechaza estacionariedad</span></span></code></pre></div>
<pre><code>## [1] 0.01</code></pre>
<p>En este caso podemos evidenciar que las dos pruebas miran la estacionariedad desde lados opuestos:</p>
<p>La ADF busca evidencia de que hay una tendencia aleatoria, y si la p-value es baja, dice que no la hay → entonces la serie es estacionaria.</p>
<p>La KPSS parte diciendo que la serie sí es estacionaria, y si la p-value es baja, entonces te dice no confíes, no lo es.</p>
<p>ADF = 0.01 ⇒ la serie podría ser estacionaria</p>
<p>KPSS = 0.01 ⇒ la serie no lo es</p>
<p>📌 Cuando ambas pruebas contradicen, se interpreta que la serie:</p>
<p>➤ No es estacionaria en nivel,
pero podría volverse estacionaria si quitamos la tendencia
(es decir, con una diferenciación o eliminando tendencia).</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb19-1" tabindex="-1"></a>ts_qty <span class="ot">&lt;-</span> <span class="fu">ts</span>(daily_sales<span class="sc">$</span>TotalQty, <span class="at">frequency =</span> <span class="dv">7</span>)</span>
<span id="cb19-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb19-2" tabindex="-1"></a></span>
<span id="cb19-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb19-3" tabindex="-1"></a>ts_diff1 <span class="ot">&lt;-</span> <span class="fu">diff</span>(ts_qty, <span class="dv">1</span>)</span>
<span id="cb19-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb19-4" tabindex="-1"></a></span>
<span id="cb19-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb19-5" tabindex="-1"></a><span class="co"># Graficamos para ver cómo luce</span></span>
<span id="cb19-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb19-6" tabindex="-1"></a><span class="fu">autoplot</span>(ts_diff1) <span class="sc">+</span> </span>
<span id="cb19-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb19-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Serie diferenciada (orden 1)&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Diferencias&quot;</span>)</span></code></pre></div>
<p><img src="series-online-retail_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb20-1" tabindex="-1"></a><span class="co"># Nuevas pruebas</span></span>
<span id="cb20-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb20-2" tabindex="-1"></a><span class="fu">adf.test</span>(ts_diff1)</span></code></pre></div>
<pre><code>## Warning in adf.test(ts_diff1): p-value smaller than printed p-value</code></pre>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_diff1
## Dickey-Fuller = -10.57, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb23-1" tabindex="-1"></a><span class="fu">kpss.test</span>(ts_diff1, <span class="at">null =</span> <span class="st">&quot;Level&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in kpss.test(ts_diff1, null = &quot;Level&quot;): p-value greater than printed
## p-value</code></pre>
<pre><code>## 
##  KPSS Test for Level Stationarity
## 
## data:  ts_diff1
## KPSS Level = 0.034586, Truncation lag parameter = 5, p-value = 0.1</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb26-1" tabindex="-1"></a><span class="fu">adf.test</span>(ts_diff1)</span></code></pre></div>
<pre><code>## Warning in adf.test(ts_diff1): p-value smaller than printed p-value</code></pre>
<pre><code>## 
##  Augmented Dickey-Fuller Test
## 
## data:  ts_diff1
## Dickey-Fuller = -10.57, Lag order = 6, p-value = 0.01
## alternative hypothesis: stationary</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb29-1" tabindex="-1"></a><span class="fu">kpss.test</span>(ts_diff1, <span class="at">null =</span> <span class="st">&quot;Level&quot;</span>)</span></code></pre></div>
<pre><code>## Warning in kpss.test(ts_diff1, null = &quot;Level&quot;): p-value greater than printed
## p-value</code></pre>
<pre><code>## 
##  KPSS Test for Level Stationarity
## 
## data:  ts_diff1
## KPSS Level = 0.034586, Truncation lag parameter = 5, p-value = 0.1</code></pre>
<p>Al aplicar las pruebas de estacionariedad a la serie original, se obtuvieron resultados contradictorios: la prueba de Dickey–Fuller aumentada (ADF) arrojó un p-valor de 0.01, indicando estacionariedad, mientras que la prueba KPSS entregó un p-valor de 0.01, rechazando la hipótesis de estacionariedad.</p>
<p>Esto sugiere que la serie no es estacionaria en nivel y presenta una tendencia determinista. Por tanto, se aplicó una diferenciación de primer orden, con el objetivo de eliminar la tendencia y estabilizar la media.</p>
<p>Posteriormente, al evaluar la serie diferenciada:</p>
<p>ADF mostró un p-valor de 0.01, lo que confirma estacionariedad, y</p>
<p>KPSS arrojó un p-valor mayor a 0.1, lo que no rechaza la estacionariedad.</p>
<p>Se concluye que la serie diferenciada es estacionaria, por lo que es adecuada para modelarse con técnicas como ARIMA o SARIMA, considerando un parámetro d = 1.</p>
<div id="transformación-box-cox" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Transformación Box-Cox<a href="predicción-de-ordenes---series-de-tiempo.html#transformación-box-cox" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb32-1" tabindex="-1"></a><span class="fu">library</span>(forecast)</span>
<span id="cb32-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb32-2" tabindex="-1"></a></span>
<span id="cb32-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb32-3" tabindex="-1"></a><span class="co"># Paso 1: Asegúrate de tener tu serie definida</span></span>
<span id="cb32-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb32-4" tabindex="-1"></a>ts_qty <span class="ot">&lt;-</span> <span class="fu">ts</span>(daily_sales<span class="sc">$</span>TotalQty, <span class="at">frequency =</span> <span class="dv">7</span>)</span>
<span id="cb32-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb32-5" tabindex="-1"></a></span>
<span id="cb32-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb32-6" tabindex="-1"></a><span class="co"># Paso 2: Calcula lambda</span></span>
<span id="cb32-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb32-7" tabindex="-1"></a>lambda <span class="ot">&lt;-</span> <span class="fu">BoxCox.lambda</span>(ts_qty)</span></code></pre></div>
<pre><code>## Warning in guerrero(x, lower, upper): Guerrero&#39;s method for selecting a Box-Cox
## parameter (lambda) is given for strictly positive data.</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb34-1" tabindex="-1"></a><span class="co"># Paso 3: Aplica la transformación</span></span>
<span id="cb34-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb34-2" tabindex="-1"></a>ts_boxcox <span class="ot">&lt;-</span> <span class="fu">BoxCox</span>(ts_qty, <span class="at">lambda =</span> lambda)</span>
<span id="cb34-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb34-3" tabindex="-1"></a></span>
<span id="cb34-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb34-4" tabindex="-1"></a><span class="co"># Paso 4: Grafica</span></span>
<span id="cb34-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb34-5" tabindex="-1"></a><span class="fu">autoplot</span>(ts_boxcox) <span class="sc">+</span></span>
<span id="cb34-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb34-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste</span>(<span class="st">&quot;Transformación Box-Cox con lambda =&quot;</span>, <span class="fu">round</span>(lambda, <span class="dv">2</span>)),</span>
<span id="cb34-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb34-7" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Ventas transformadas&quot;</span>)</span></code></pre></div>
<p><img src="series-online-retail_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Con el fin de estabilizar la varianza de la serie <code>TotalQty</code>, se aplicó una transformación Box-Cox, la cual estima automáticamente el parámetro λ (lambda). En este caso, el valor obtenido fue λ = 0.47, lo que indica que la serie original presenta cierta heterocedasticidad (variación de la varianza en el tiempo).</p>
<p>La transformación tuvo como objetivo suavizar las fluctuaciones extremas de la serie, logrando una distribución más simétrica y facilitando su uso en modelos como ARIMA o SARIMA. En el gráfico se observa una reducción parcial de los picos más altos y una mayor estabilidad en la amplitud de las oscilaciones.</p>
<p>Por tanto, se concluye que la aplicación de la transformación Box-Cox <strong>fue útil</strong> para mejorar la estructura estadística de la serie antes de su modelado.</p>
<div id="suavizamiento-exponencial-el-promedio-móvil-y-holt-winter" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Suavizamiento exponencial, el promedio móvil y Holt-Winter<a href="predicción-de-ordenes---series-de-tiempo.html#suavizamiento-exponencial-el-promedio-móvil-y-holt-winter" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>##Pronóstico con suavizamiento exponencial simple (SES)</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb35-1" tabindex="-1"></a><span class="co"># Ajuste del modelo SES (sin tendencia ni estacionalidad)</span></span>
<span id="cb35-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb35-2" tabindex="-1"></a>ses_model <span class="ot">&lt;-</span> <span class="fu">ses</span>(ts_qty, <span class="at">h =</span> <span class="dv">14</span>)</span>
<span id="cb35-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb35-3" tabindex="-1"></a></span>
<span id="cb35-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb35-4" tabindex="-1"></a><span class="co"># Gráfico de predicción SES</span></span>
<span id="cb35-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb35-5" tabindex="-1"></a><span class="fu">autoplot</span>(ses_model) <span class="sc">+</span></span>
<span id="cb35-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb35-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Pronóstico con Suavizamiento Exponencial Simple (SES)&quot;</span>,</span>
<span id="cb35-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb35-7" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Cantidad de ventas diarias&quot;</span>)</span></code></pre></div>
<p><img src="series-online-retail_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>El modelo SES fue ajustado a la serie de ventas diarias con el objetivo de generar un pronóstico de corto plazo a 14 días. Este modelo da mayor peso a los valores recientes, sin considerar explícitamente ni la tendencia ni la estacionalidad.</p>
<p>En el gráfico se observa:
- La línea negra representa los datos históricos.
- La franja azul representa el pronóstico del modelo.
- La banda azul más clara indica el intervalo de confianza del 95%.</p>
<p>Se evidencia que el modelo SES <strong>no capta adecuadamente la tendencia creciente ni la estacionalidad semanal</strong>, lo cual era esperable dado que este modelo es más apropiado para series sin patrones complejos. Aun así, sirve como modelo base de comparación para métodos más avanzados como Holt-Winters.</p>
</div>
</div>
<div id="pronóstico-con-modelo-holt-winters-aditivo" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Pronóstico con modelo Holt-Winters aditivo<a href="predicción-de-ordenes---series-de-tiempo.html#pronóstico-con-modelo-holt-winters-aditivo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb36-1" tabindex="-1"></a><span class="do">## --- Modelo Holt-Winters aditivo (con tendencia y estacionalidad) ---</span></span>
<span id="cb36-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb36-2" tabindex="-1"></a><span class="co"># Ajuste del modelo Holt-Winters (estacionalidad semanal: frecuencia = 7)</span></span>
<span id="cb36-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb36-3" tabindex="-1"></a>hw_model <span class="ot">&lt;-</span> <span class="fu">hw</span>(ts_qty, <span class="at">seasonal =</span> <span class="st">&quot;additive&quot;</span>, <span class="at">h =</span> <span class="dv">14</span>)</span>
<span id="cb36-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb36-4" tabindex="-1"></a></span>
<span id="cb36-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb36-5" tabindex="-1"></a><span class="co"># Gráfico de predicción Holt-Winters</span></span>
<span id="cb36-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb36-6" tabindex="-1"></a><span class="fu">autoplot</span>(hw_model) <span class="sc">+</span></span>
<span id="cb36-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb36-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Pronóstico con modelo Holt-Winters aditivo (14 días)&quot;</span>,</span>
<span id="cb36-8"><a href="predicción-de-ordenes---series-de-tiempo.html#cb36-8" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&quot;Cantidad de ventas diarias&quot;</span>)</span></code></pre></div>
<p><img src="series-online-retail_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
<p>Se ajustó el modelo Holt-Winters en su versión aditiva, el cual considera tanto la tendencia como la estacionalidad de la serie. Este modelo es ideal cuando la estacionalidad tiene un efecto constante (suma en lugar de multiplicación), como ocurre con la serie de ventas diarias analizada, la cual presenta un patrón de comportamiento semanal.</p>
<p>En el gráfico se observa:
- La línea negra representa los datos históricos.
- La línea azul muestra el pronóstico a 14 días.
- La banda azul más clara corresponde al intervalo de confianza del 95%.</p>
<p>Comparado con el modelo SES, Holt-Winters ofrece un pronóstico más coherente con el comportamiento observado, ya que incorpora la tendencia creciente y el ciclo semanal. Por tanto, se considera una mejor alternativa para la proyección de esta serie.</p>
</div>
<div id="evaluación-y-comparación-de-precisión-ses-vs-holt-winters" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Evaluación y comparación de precisión: SES vs Holt-Winters<a href="predicción-de-ordenes---series-de-tiempo.html#evaluación-y-comparación-de-precisión-ses-vs-holt-winters" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para evaluar la calidad del pronóstico generado por los modelos de suavizamiento aplicados (SES y Holt-Winters aditivo), se calcularon las principales métricas de error sobre el conjunto de entrenamiento. Estas métricas incluyen:</p>
<ul>
<li><strong>ME (Mean Error)</strong>: Error promedio. Idealmente debe ser cercano a cero.</li>
<li><strong>RMSE (Root Mean Squared Error)</strong>: Penaliza los errores grandes. Mientras más bajo, mejor.</li>
<li><strong>MAE (Mean Absolute Error)</strong>: Promedio de los errores absolutos, útil para interpretar la magnitud de los errores.</li>
<li><strong>MAPE (Mean Absolute Percentage Error)</strong>: Error porcentual promedio. Útil para interpretar errores en escala relativa.</li>
<li><strong>MASE (Mean Absolute Scaled Error)</strong>: Escala el error absoluto frente a un modelo naïve. Valores menores a 1 indican un mejor desempeño que el modelo naïve.</li>
<li><strong>ACF1</strong>: Autocorrelación del residuo en el primer rezago. Idealmente debe ser cercana a cero para garantizar independencia en los errores.</li>
</ul>
<p>En la siguiente tabla se resumen los resultados de cada modelo:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb37-1" tabindex="-1"></a><span class="co"># Comparar precisión de los modelos usando métricas estándar</span></span>
<span id="cb37-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb37-2" tabindex="-1"></a><span class="fu">accuracy</span>(ses_model)</span></code></pre></div>
<pre><code>##                   ME     RMSE      MAE       MPE     MAPE      MASE       ACF1
## Training set 450.271 7739.627 5680.052 -26.05599 50.93325 0.6752243 0.02316609</code></pre>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb39-1" tabindex="-1"></a><span class="fu">accuracy</span>(hw_model)</span></code></pre></div>
<pre><code>##                    ME     RMSE      MAE       MPE     MAPE      MASE       ACF1
## Training set 380.1101 7705.517 5653.429 -24.52434 50.07191 0.6720594 0.02793278</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-1" tabindex="-1"></a><span class="co"># Guardar resultados</span></span>
<span id="cb41-2"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-2" tabindex="-1"></a>ses_acc <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(ses_model)</span>
<span id="cb41-3"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-3" tabindex="-1"></a>hw_acc  <span class="ot">&lt;-</span> <span class="fu">accuracy</span>(hw_model)</span>
<span id="cb41-4"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-4" tabindex="-1"></a></span>
<span id="cb41-5"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-5" tabindex="-1"></a><span class="co"># Unir en una sola tabla</span></span>
<span id="cb41-6"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-6" tabindex="-1"></a>accuracy_comparison <span class="ot">&lt;-</span> <span class="fu">rbind</span>(</span>
<span id="cb41-7"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-7" tabindex="-1"></a>  <span class="at">SES =</span> ses_acc,</span>
<span id="cb41-8"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-8" tabindex="-1"></a>  <span class="at">HoltWinters =</span> hw_acc</span>
<span id="cb41-9"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-9" tabindex="-1"></a>)</span>
<span id="cb41-10"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-10" tabindex="-1"></a></span>
<span id="cb41-11"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-11" tabindex="-1"></a><span class="co"># Mostrar con formato bonito</span></span>
<span id="cb41-12"><a href="predicción-de-ordenes---series-de-tiempo.html#cb41-12" tabindex="-1"></a><span class="fu">kable</span>(accuracy_comparison, <span class="at">digits =</span> <span class="dv">2</span>, <span class="at">caption =</span> <span class="st">&quot;Comparación de métricas de precisión: SES vs Holt-Winters&quot;</span>)</span></code></pre></div>
<table>
<caption><span id="tab:unnamed-chunk-11">Table 3.1: </span>Comparación de métricas de precisión: SES vs Holt-Winters</caption>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">ME</th>
<th align="right">RMSE</th>
<th align="right">MAE</th>
<th align="right">MPE</th>
<th align="right">MAPE</th>
<th align="right">MASE</th>
<th align="right">ACF1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Training set</td>
<td align="right">450.27</td>
<td align="right">7739.63</td>
<td align="right">5680.05</td>
<td align="right">-26.06</td>
<td align="right">50.93</td>
<td align="right">0.68</td>
<td align="right">0.02</td>
</tr>
<tr class="even">
<td align="left">Training set</td>
<td align="right">380.11</td>
<td align="right">7705.52</td>
<td align="right">5653.43</td>
<td align="right">-24.52</td>
<td align="right">50.07</td>
<td align="right">0.67</td>
<td align="right">0.03</td>
</tr>
</tbody>
</table>
<div id="análisis" class="section level3 hasAnchor" number="3.3.1">
<h3><span class="header-section-number">3.3.1</span> Análisis:<a href="predicción-de-ordenes---series-de-tiempo.html#análisis" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los resultados muestran que el modelo Holt-Winters aditivo supera ligeramente
al modelo de suavizamiento exponencial simple (SES) en la mayoría de las métricas:</p>
<ul>
<li><p>El RMSE del modelo Holt-Winters fue de 7705.5, ligeramente inferior al 7739.6 del SES.
Esto implica que el modelo Holt-Winters logra minimizar de mejor forma los errores grandes.</p></li>
<li><p>La métrica MAPE, que refleja el error porcentual promedio, fue de 50.07% en Holt-Winters
frente a 50.93% en SES. Aunque la diferencia es leve, favorece al modelo que incorpora
tendencia y estacionalidad.</p></li>
<li><p>El MAE también es ligeramente más bajo en Holt-Winters, confirmando un menor error promedio absoluto.</p></li>
<li><p>En términos de MASE, ambos modelos tienen valores inferiores a 1 (SES = 0.6752,
Holt-Winters = 0.6721), lo cual indica que ambos superan a un modelo naïve.
No obstante, Holt-Winters lo hace con mayor eficiencia.</p></li>
<li><p>Finalmente, los valores de ACF1 son cercanos a cero en ambos modelos, lo que indica que
los errores no presentan autocorrelación significativa, cumpliendo con uno de los supuestos
básicos de los modelos de pronóstico.</p></li>
</ul>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="introducción.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/02-literature.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["series-online-retail.pdf", "series-online-retail.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
